tdefontinst, fix FTBFS undefined reference to symbol 'FT_Get_Sfnt_Name_Count'
Signed-off-by: gregory guy <gregory-tde@laposte.net>
(cherry picked from commit 9f0628564db959dc3dbc3c8e9cd9efc99d8c3bfd)