Added missing header in ksysguard/ksysguardd/Linux/netstat.c
Without the header, the build log:

[ 96%] Building C object ksysguard/ksysguardd/Linux/CMakeFiles/ksysguardd-static.dir/netstat.c.o
/usr/src/qi/build/tdebase-trinity-14.0.7/ksysguard/ksysguardd/Linux/netstat.c: In function ‘updateNetStatTcpUdpRaw’:
/usr/src/qi/build/tdebase-trinity-14.0.7/ksysguard/ksysguardd/Linux/netstat.c:269:2: error: unknown type name ‘uint’; did you mean ‘int’?
  269 |  uint local_addr, local_port;
      |  ^~~~
      |  int
/usr/src/qi/build/tdebase-trinity-14.0.7/ksysguard/ksysguardd/Linux/netstat.c:270:2: error: unknown type name ‘uint’; did you mean ‘int’?
  270 |  uint remote_addr, remote_port;
      |  ^~~~
      |  int
/usr/src/qi/build/tdebase-trinity-14.0.7/ksysguard/ksysguardd/Linux/netstat.c:272:2: error: unknown type name ‘uint’; did you mean ‘int’?
  272 |  uint state;
      |  ^~~~
      |  int
make[2]: *** [ksysguard/ksysguardd/Linux/CMakeFiles/ksysguardd-static.dir/build.make:180: ksysguard/ksysguardd/Linux/CMakeFiles/ksysguardd-static.dir/netstat.c.o] Error 1
make[2]: Leaving directory '/usr/src/qi/build/tdebase-trinity-14.0.7/BUILD'
make[1]: *** [CMakeFiles/Makefile2:24044: ksysguard/ksysguardd/Linux/CMakeFiles/ksysguardd-static.dir/all] Error 2
make[1]: Leaving directory '/usr/src/qi/build/tdebase-trinity-14.0.7/BUILD'
make: *** [Makefile:130: all] Error 2

Signed-off-by: Matías Fonzo <selk@dragora.org>